modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="damage_control"
version="${version}"
displayName="Damage Control"
authors="Aether_254"
description='''Protects large container spills inside persistent, leashable damaged packages.'''

[[dependencies.damage_control]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.damage_control]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.damage_control]]
modId="create"
type="required"
versionRange="[6.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.damage_control]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"
